receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      disk:
      network:

processors:
  batch:

exporters:
  debug:
    verbosity: normal
  # --- ADDED THIS ---
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      # --- UPDATED THIS ---
      exporters: [debug, prometheus]
