---
- name: install jenkins
  hosts: all
  become: yes
  gather_facts: no  # Keep this NO
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: 1. Bootstrap Python and Dependencies (RAW)
      raw: apt-get update && apt-get install -y python3-minimal python3-apt curl gnupg fontconfig openjdk-17-jre
      changed_when: false

    - name: 2. Add Jenkins Key and Repo (RAW)
      raw: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: 3. Install and Start Jenkins (RAW)
      raw: |
        apt-get update && \
        apt-get install -y jenkins && \
        systemctl daemon-reload && \
        systemctl enable jenkins && \
        systemctl restart jenkins
